- hosts: windows
  roles:
    - roles/windows
  vars_prompt:
    - name: oracle_client_version_to_install
      prompt: "Ingrese la versión de Oracle Client a instalar (por ejemplo, 19_22, 21_1)"
      private: no

# ansible-playbook playbooks/install_windows.yml -i inventory/inventario.ini
